# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf9be8834d267139bd253d6202959a1b7010a4e78c72e2ab5e43e2df1496c9495880ab9085e1fbfe449ae257d2b188fac5dbe63e03f3f0cd732de548f5b2a603

test:
  secret_key_base: 046767c640206af4fac5e5a749a65627b7902c0d0a5161ec5911f90351b84ce7bee21cbcbed4b2d463fe4777617a67a74670b6b6a5d58cd5f708a555cff3218c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
